# Effectively Modern Humbug. For 1.10 ground up.

configuration_file_version: 1

debug: true
broadcast_permission: simpleadmin.broadcast

hacks:
  Experimental:
    enabled: true
    combatspy: false
    teleportspy: false
    postteleport:
      spy: false
      count: 10
  GameFeatures:
    enabled: true
    disablePotatoXP: false
    # Villager trading is not like above and true = able to trade and false = not able
    villagerTrading: false
    # Wither spawn is also true = enabled and false = disabled
    witherSpawning: false
    # Prevent or allow pillager patrols from spawning
    # Patrols spawning is also true = enabled and false = disabled
    patrolSpawning: false
    # Phantom spawn is also true = enabled and false = disabled
    phantomSpawning: false
    # Enderchests is also true = enabled and false = disabled
    enderChestPlacement: true
    enderChestUse: false
    # ElytraUse: true  = enabled, false = disabled
    elytraUse: true
    chorusFruitTeleportation: false
    # WeepingAngel bans people when they die, the numbers are in minutes.
    weepingAngel:
      enabled: false
      environment: 1
      playerKill: 5
    # prevent use of buckets or dispensing water in hell biomes
    blockWaterInHell: true
    minecartTeleport: true
    obsidianGenerators: true
    personalDeathMessages: true
    goldBlockTeleport: false
  GameFixes:
    enabled: true
    # Does not fully work atm
    blockElytraBreakBug: false
    damageOnElytraBreakBug: 1.0
    canStorageTeleport: false
    stopHopperDupe: true
    stopRailDupe: true
    stopEndPortalDeletion: true
    stopBedBombingInHellBiomes: true
    stopAnchorBombing: true
    preventTreeWraparound: true
    fixPearlGlitch: true
  GameTuning:
    enabled: true
    chunkLimits:
      enabled: true
      exceededMessage: '&9Limit reached for this chunk, you cannot place more of this type of block.'
      tileEntities:
        HOPPER: 4
        PISTON: 4
        STICKY_PISTON: 4
        DISPENSER: 4
        DROPPER: 4
        COMPARATOR: 4
        OBSERVER: 2
      exempt:
      - Steve
      - Alex
    daytimeBed:
      enabled: true
      spawnSetMessage: '&7Your spawn has been set.'
    # Makes nether ratio 1 to 1
    oneToOneNether: false
    # Return nether portal, true = enabled    false = disabled
    returnNetherPortal: true
    allowNetherTravel: false
    # Disables minecart inventories (trying to fix dupe issues)
    # enabled = able to right click   disabled = not able to right click
    chestedMinecartInventories: true
    hopperMinecartInventories: true
    enderChestInventories: false
    stopTrapHorses: true
    killTrapHorses: true
    changeSpawnerType: false
    allowVillagerTrading: false
    enderGrief: false
    witherGrief: false
    dragonGrief: true
    allowEnchantedApples: false
    preventFallingThroughBedrock: true
    # Disable the Bad Omen effect that player receive when killing pillager patrols
    badOmen: false
    #a list of materials players shouldn't be allowed to place at all
    noplace:
     - DRAGON_EGG
    rainReduction:
      enabled: false
      rainOccurrenceChance: .5
  CTAnnounce:
    enabled: false
    delay: 10000
    message: '%Victim% was combat tagged by %Attacker%'
    broadcast: [OP, CONSOLE]
  NewfriendAssist:
    enabled: true
    announce: '&f%Player% is brand new!'
    broadcast: [PERM, CONSOLE]
    helptips: on
    helptips_end: 20m
    introkit:
      enabled: true
      contents:
       - ==: org.bukkit.inventory.ItemStack
         v: 1
         type: COOKIE
         amount: 32
         meta:
           ==: ItemMeta
           meta-type: UNSPECIFIC
           display-name: 'Manna'
           lore:
            - "Gift from the Admins as you"
            - "begin your journey."
       - ==: org.bukkit.inventory.ItemStack
         v: 1
         type: BED
         amount: 1
         meta:
           ==: ItemMeta
           meta-type: UNSPECIFIC
           lore:
            - "This world is unforgiving."
            - "Be sure to get a good night's"
            - "rest soon."
  Introbook:
    enabled: true
    follow: true
    contents:
      title: Welcome, ${player}
      author: Bonkill
      pages:
       - "   &oWelcome, ${player}!"
       - "    &oWhat is this place?\n\"A new type of Minecraft server built towards providing a competitive, high stakes, immersive experience controlled by the players.\"&r\n-Scuwr, server owner"
       - "    &oWhat is this place?&r\n&lNOT just survival&r\nAdmins are hands-off and only handle glitches and hackers\n&lNOT just chaos&r\nPlugins allow players and towns to enforce their own rules\n&lNOT just roleplay&r\nNobody pretends -- conflict is genuine and heated"
       - "    &oBasic Mechanics&r\n-The world is custom generated\n-Many custom biomes\n-Limited chat range\n-Respawn in random area unless you sleep\n-Mobs spawn sparsely\n-Vanilla Nether\n-Ore veins and custom ore spawning."
       - "   &oMods&r\n   &lCitadel&r:\n Reinforces things so it takes numerous breaks to destroy them. Locks some things too.\n&lMore Info:&r &oVisual Guide:&r imgur.com/BnlL2 &oWiki Page:&r tinyurl.com/citadelmod\n&oType \"/help citadel\" in chat to get commands"
       - "   &lPrison Pearl&r:\n Ender Pearls trap players in the end. Others can steal back your pearl and free you -- you always know where it is so they cannot hide it\n&lMore Info:&r &oVisual Guide:&r imgur.com/XbhkK &oWiki Page:&r tinyurl.com/prisperl"
       - "   &lJuke Alert&r:\n Creates 'Juke' blocks that record player activity in radius. If you steal, grief, or trespass -- people will know about it & put a bounty for you to be pearled.\n&lMore Info:&r &oWiki Page:&r tinyurl.com/snitchblock"
       - "   &lMythicMobs&r:\n Some custom mobs to increase the risk and thrill on specific islands and areas throughout Devoted.\n&lMore Info:&r &oBukkit Page:&r dev.bukkit.org/bukkit-plugins/mythicmobs"
       - "   &lItem Exchange&r:\n It's a minecraft shop mod that enables different chests (and other inventory blocks) to perform an exchange of items with a player.\n&lMore Info:&r &oWiki Page:&r tinyurl.com/itemxchng"
       - "   &lHumbug&r:\n Disables some features of minecraft -- see wiki for short list. Please read it to ensure you don't waste resources on a useless block.\n&lMore Info:&r &oWiki Page:&r tinyurl.com/humbugwiki"
       - "   &lRealistic Biomes&r:\n Biomes are large, crops grow different in different biomes. Hit ground with seed to see growth rate. Farms need sunlight. Crops grow with nobody around.\n&lMore Info:&r &oWiki Page:&r tinyurl.com/realbiome"
       - "   &lArthropod Egg&r:\n Allows you to capture passive mobs into spawn eggs using Bane of Arthropod enchantment.\n&lMore Info:&r &oGithub Page:&r tinyurl.com/arthrop"
       - "   &lBrewery&r:\n Custom brewing of booze and more.\n&lMore Info:&r &oBukkit Page:&r tinyurl.com/bukkitbrewp"
       - "   &oFurther Info&r\nVisit our subreddit at: &oreddit.com/r/Devoted&r"
       - "We extend our appreciation to the devs, admins, and players at: &oreddit.com/r/Civcraft"
  HackBot:
    enabled: false
    bots:
      Rando:
        name: Rando4800xXx
        skin: DeepCopy
        spawnLocation:
          ==: org.bukkit.Location
          yaw: 0.0
          pitch: 0.0
          z: 50.0
          y: 40.0
          world: world
          x: 50.0
        alive: false
        location:
          ==: org.bukkit.Location
          yaw: 0.0
          pitch: 0.0
          z: 50.0
          y: 40.0
          world: world
          x: 50.0
  InvControl:
    enabled: true
  InvisibleFixTwo:
    enabled: false
    # in ticks -- ticks to wait after teleport to force update
    teleportDelay: 5
    # in milliseconds -- min time between forced updates if active
    minInterval: 100
    ignoreOps: true
    ignorePermission: sah.allowInvisible
  InvisibleFix:
    enabled: false
    ignoreOps: true
    ignorePermission: sah.allowInvisible
    # in ticks
    recheckInterval: 500
  ReinforcedChestBreak:
    enabled: true
    # in seconds
    delay: 180
    message: "&4%player% is raiding a chest at %x% %y% %z%."
  SanityHack:
    enabled: true
    trackPlace: true
    trackBreak: true
    belowYLevel: 7
  TimingsHack:
    enabled: true
  BadBoyWatch:
    enabled: true
    trackingDepth: 16
    clearOnMatch: true
    watchedMaterials:
     - CHEST
     - FURNACE
     - DROPPER
     - DISPENSER
     - JUKEBOX
     - NOTE_BLOCK
     - BEACON
     - ENDER_CHEST
     - SPONGE
     - HOPPER
     - PISTON
     - STICKY_PISTON
     - OBSERVER
  Insight:
    enabled: false
    into:
    - org.bukkit.event.player
    - org.bukkit.event.entity
    - org.bukkit.event.block
    - org.bukkit.event.inventory
    - org.bukkit.event.enchantment
    - org.bukkit.event.hanging
    - org.bukkit.event.painting
    - org.bukkit.event.vehicle
    - org.bukkit.event.weather
    - org.bukkit.event.world
  ToggleLamp:
    enabled: false
    cooldownTime: 100
  HorseStats:
    enabled: false
    wand: COMPASS
  AutoRespawn:
    enabled: true
    # Delay in MS
    # Default: 300000 (five minutes)
    respawnDelay: 300000
    # The respawn delay (in MS) if someone logs in dead
    # Default 0 (instant)
    loginRespawnDelay: 0
    # Jokey joke messages sent to the player if auto-respawned
    # Deactivate by removing all the quotes below
    respawnQuotes:
    - <gold>Wait... how did I get here?
    - <gold>Must've been a rough night o.o
    - <gold>Why does my entire body ache?
    - <gold>That <it>really<gold> hurt!
  AntiFastBreak:
    enabled: true
    breakDenyDuration: 3000
    laggLenciency: 1.2
  PhantomMenace:
    enabled: true
    # Players have a statistic called TIME_SINCE_REST. If a player's value is above 72k (3 days minecraft time) then
    # they will start spawning phantoms. Setting the cap to below 72k will effectively disable phantoms. Setting the
    # cap to -1 will disable the cap. Default: 80k (10% chance per two minutes during the night and thunder storms.)
    # Read more here: https://minecraft.gamepedia.com/Phantom#Java_Edition
    timeSinceRestCap: 80000
    # Determines whether phantoms are allowed to spawn during the night.
    nightSpawn: true
    # Determines whether phantoms are allowed to spawn during thunder storms.
    stormSpawn: true
  PlayerStatistics:
    enabled: true
  PlayerRevive:
    enabled: true
  EventDebugHack:
    enabled: true
  EventHandlerList:
    enabled: true
  DebugWand:
    enabled: true
  BuffSpanker:
    enabled: true
    # The list of PotionEffectType's that you do not wish players to receive.
    naughty:
      - DOLPHINS_GRACE
      - BAD_OMEN
      - SLOW_DIGGING
      - SLOW_FALLING
  ShipOutOfLuck:
    enabled: true
    # The list of Material's that boats cannot be placed on and will eject passengers
    boatBreakers:
      - ICE
      - PACKED_ICE
      - FROSTED_ICE
      - BLUE_ICE
